# Generated by Django 2.2.2 on 2019-08-02 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemGroupName', models.CharField(max_length=120)),
                ('GroupShortName', models.CharField(max_length=5)),
                ('IsActive', models.BooleanField(default=True)),
                ('IsDelete', models.BooleanField(default=False)),
                ('CreateBy', models.CharField(max_length=500)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateBy', models.CharField(blank=True, max_length=500, null=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True, null=True)),
                ('DeleteBy', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UomDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UomDetailsName', models.CharField(max_length=500)),
                ('UomDetailsShortName', models.CharField(max_length=500)),
                ('ConversionValue', models.DecimalField(decimal_places=3, default=1, max_digits=18)),
                ('EqualToMaster', models.BooleanField(default=False)),
                ('IsActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UomMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UomMasterName', models.CharField(max_length=500)),
                ('UomMasterShortName', models.CharField(max_length=500)),
                ('IsActive', models.BooleanField(default=True)),
                ('IsDelete', models.BooleanField(default=False)),
                ('CreateBy', models.CharField(blank=True, max_length=500)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateBy', models.CharField(blank=True, max_length=500)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
                ('DeleteBy', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UomDetailsUpdateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UomDetailsName', models.CharField(max_length=500)),
                ('UomDetailsShortName', models.CharField(max_length=500)),
                ('ConversionValue', models.DecimalField(decimal_places=3, default=1, max_digits=18)),
                ('EqualToMaster', models.BooleanField(default=False)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('CreateBy', models.CharField(blank=True, max_length=500)),
                ('UomDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BasicSettings.UomDetails')),
                ('UomMaster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BasicSettings.UomMaster')),
            ],
        ),
        migrations.AddField(
            model_name='uomdetails',
            name='UomMaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicSettings.UomMaster'),
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemCategory', models.CharField(max_length=120)),
                ('CategoryShortName', models.CharField(max_length=5)),
                ('IsDelete', models.BooleanField(default=False)),
                ('CreateBy', models.CharField(max_length=500)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateBy', models.CharField(blank=True, max_length=500, null=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True, null=True)),
                ('DeleteBy', models.CharField(blank=True, max_length=500, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('ItemGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicSettings.ItemGroup')),
            ],
        ),
    ]
