# Generated by Django 2.2.2 on 2019-08-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicSettings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemBrandName', models.CharField(max_length=500)),
                ('IsActive', models.BooleanField(default=True)),
                ('IsDelete', models.BooleanField(default=False)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('CreateBy', models.CharField(blank=True, max_length=500)),
                ('DeleteDate', models.DateTimeField(blank=True)),
                ('DeleteBy', models.CharField(blank=True, max_length=500)),
                ('UpdateBy', models.CharField(blank=True, max_length=500)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemColorName', models.CharField(max_length=500)),
                ('IsActive', models.BooleanField(default=True)),
                ('IsDelete', models.BooleanField(default=False)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('CreateBy', models.CharField(blank=True, max_length=500)),
                ('DeleteDate', models.DateTimeField(blank=True)),
                ('DeleteBy', models.CharField(blank=True, max_length=500)),
                ('UpdateBy', models.CharField(blank=True, max_length=500)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemSizeName', models.CharField(max_length=500)),
                ('IsActive', models.BooleanField(default=True)),
                ('IsDelete', models.BooleanField(default=False)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('CreateBy', models.CharField(blank=True, max_length=500)),
                ('DeleteDate', models.DateTimeField(blank=True)),
                ('DeleteBy', models.CharField(blank=True, max_length=500)),
                ('UpdateBy', models.CharField(blank=True, max_length=500)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
