# Generated by Django 2.2.2 on 2019-08-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicSettings', '0002_itembrand_itemcolor_itemsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryName', models.CharField(max_length=500)),
                ('CountryShortName', models.CharField(max_length=5)),
                ('IsActive', models.BooleanField(default=True)),
                ('IsDelete', models.BooleanField(default=False)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('CreateBy', models.CharField(blank=True, max_length=500)),
                ('UpdateBy', models.CharField(blank=True, max_length=500)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
                ('DeleteDate', models.DateTimeField(blank=True)),
                ('DeleteBy', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
