# Generated by Django 2.2.2 on 2019-08-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicSettings', '0003_countryorigin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembrand',
            name='DeleteBy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='itembrand',
            name='DeleteDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
