# Generated by Django 2.2.2 on 2019-08-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicSettings', '0004_auto_20190823_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcolor',
            name='DeleteBy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='itemcolor',
            name='DeleteDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
