# Generated by Django 2.2.2 on 2019-08-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicSettings', '0005_auto_20190823_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsize',
            name='ItemSizeName',
            field=models.CharField(max_length=1000),
        ),
    ]
