# Generated by Django 2.2.2 on 2019-09-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StepCount', models.CharField(max_length=50)),
                ('StepName', models.CharField(max_length=50)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('CreateBy', models.CharField(blank=True, max_length=500)),
                ('UpdateBy', models.CharField(blank=True, max_length=500, null=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True, null=True)),
                ('DeleteDate', models.DateTimeField(blank=True, null=True)),
                ('DeleteBy', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MeneType', models.CharField(max_length=800)),
                ('IsDelete', models.BooleanField(default=False)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('CreateBy', models.CharField(blank=True, max_length=500)),
                ('UpdateBy', models.CharField(blank=True, max_length=500, null=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True, null=True)),
                ('DeleteDate', models.DateTimeField(blank=True, null=True)),
                ('DeleteBy', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MenuName', models.CharField(max_length=800)),
                ('UrlName', models.CharField(max_length=800)),
                ('OrderNo', models.IntegerField(default=0)),
                ('ParentMenu', models.IntegerField(default=0)),
                ('IsActive', models.BooleanField(default=True)),
                ('IsDelete', models.BooleanField(default=False)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('CreateBy', models.CharField(blank=True, max_length=500)),
                ('UpdateBy', models.CharField(blank=True, max_length=500, null=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True, null=True)),
                ('DeleteDate', models.DateTimeField(blank=True, null=True)),
                ('DeleteBy', models.CharField(blank=True, max_length=500, null=True)),
                ('MenuStep', models.ForeignKey(on_delete=0, to='MenuSetup.MenuStep')),
                ('MenuType', models.ForeignKey(on_delete=0, to='MenuSetup.MenuType')),
            ],
        ),
    ]
