# Generated by Django 2.2.2 on 2019-09-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuSetup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menustep',
            name='StepCount',
            field=models.IntegerField(unique=True),
        ),
    ]
