# Generated by Django 2.2.2 on 2019-09-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MenuSetup', '0003_auto_20190913_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menustep',
            name='DeleteBy',
        ),
        migrations.RemoveField(
            model_name='menustep',
            name='DeleteDate',
        ),
    ]
