# Generated by Django 2.2.2 on 2019-09-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuSetup', '0005_auto_20190914_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmenu',
            name='UrlName',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
