# Generated by Django 2.2.2 on 2019-09-13 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MenuSetup', '0006_auto_20190914_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmenu',
            name='ParentMenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appMenu', to='MenuSetup.AppMenu'),
        ),
        migrations.AlterField(
            model_name='appmenu',
            name='UrlName',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
