# Generated by Django 2.2.2 on 2019-09-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuSetup', '0007_auto_20190914_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmenu',
            name='ParentMenu',
            field=models.IntegerField(default=0),
        ),
    ]
