# Generated by Django 2.2.2 on 2019-09-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicSettings', '0007_auto_20190823_2212'),
        ('ProductSetup', '0002_auto_20190823_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='ProductColor',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='ProductColor',
            field=models.ManyToManyField(to='BasicSettings.ItemColor'),
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='ProductSize',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='ProductSize',
            field=models.ManyToManyField(to='BasicSettings.ItemSize'),
        ),
    ]
