# Generated by Django 2.2.2 on 2019-09-12 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSetup', '0003_auto_20190906_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='DeleteBy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='DeleteDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='ProductBrand',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BasicSettings.ItemBrand'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='ProductColor',
            field=models.ManyToManyField(blank=True, to='BasicSettings.ItemColor'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='ProductDescripTion',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='ProductSize',
            field=models.ManyToManyField(blank=True, to='BasicSettings.ItemSize'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='ProductSpecification',
            field=models.CharField(max_length=8000),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='UpdateBy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='UpdateDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
