# Generated by Django 2.2.2 on 2019-09-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductSetup', '0004_auto_20190913_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='ProductColor',
            field=models.ManyToManyField(blank=True, null=True, to='BasicSettings.ItemColor'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='ProductSize',
            field=models.ManyToManyField(blank=True, null=True, to='BasicSettings.ItemSize'),
        ),
    ]
